image: node:12.6.0-stretch

test:
  only:
    - merge_requests
  before_script:
    - npm install
  script:
    - npm test

release:
  image: buildpack-deps:stretch
  only:
    - release@getto-systems-labo/blog
  script:
    - ./bin/push_tags.sh
